name: Release

on:
  workflow_dispatch:
    inputs:
      tags:
        description: "Version tags"
  push:
    branches: [main]

env:
  VERSION: 0.9.0

jobs:
  release:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: pack
        run: |
          rm -rf ./.git
          rm -rf ./.github
          zip -q -r yao-amis-admin-${{ env.VERSION }}.zip *

      - name: Create Draft Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: yao-amis-admin-${{ env.VERSION }}
          release_name: yao-amis-admin-${{ env.VERSION }}
          draft: true
          prerelease: false

      - uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: yao-amis-admin-${{ env.VERSION }}.zip
          asset_name: yao-amis-admin-${{ env.VERSION }}.zip
          asset_content_type: application/zip

      - uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
